// Pure, framework-free helper that turns a node-sql-parser error into a
// human-friendly message with a 1-based line/column when it can be
// determined. Tool-specific.
//
// node-sql-parser's parser is generated by PEG.js. On a parse failure it
// throws an error shaped like `{ name: 'SyntaxError', message, location:
// { start: { line, column, offset }, end: {...} } }` (verified against the
// installed node-sql-parser@5.4.0 at runtime — see AGENT NOTES in this repo's
// history). Errors from other causes (e.g. an unsupported dialect string)
// are plain Errors with no `location`.

export interface SqlErrorInfo {
  /** The raw error message. */
  message: string;
  /** 1-based line number, or null if it could not be determined. */
  line: number | null;
  /** 1-based column number, or null if it could not be determined. */
  column: number | null;
}

interface PegLikeLocation {
  start?: { line?: unknown; column?: unknown };
}

function hasPegLocation(error: unknown): error is { location?: PegLikeLocation } {
  return typeof error === 'object' && error !== null && 'location' in error;
}

/** Extracts line/column info from a node-sql-parser (PEG.js) parse error. */
export function describeSqlError(error: unknown): SqlErrorInfo {
  const message = error instanceof Error ? error.message : String(error);

  if (hasPegLocation(error)) {
    const start = error.location?.start;
    const line = typeof start?.line === 'number' ? start.line : null;
    const column = typeof start?.column === 'number' ? start.column : null;
    if (line !== null && column !== null) {
      return { message, line, column };
    }
  }

  return { message, line: null, column: null };
}

/** Formats a SqlErrorInfo into a single display string. */
export function formatSqlErrorInfo(info: SqlErrorInfo): string {
  if (info.line !== null && info.column !== null) {
    return `${info.message} (line ${info.line}, column ${info.column})`;
  }
  return info.message;
}
